spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    port: 6379
  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: showStatus
      logic-delete-value: 0
      logic-not-delete-value: 1

server:
      port: 10001
      logging:
        level:
          com.jc.gulimall: error
      feign:
        client:
          config:
      default:
        connectTimeout: 10000
        readTimeout: 600000